# Generated by Django 5.0.1 on 2025-10-01 17:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('empresa', 'Empresa'), ('alumno', 'Alumno/Exalumne')], default='alumno', max_length=10, verbose_name='Rol')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('cicle', models.CharField(choices=[('DAM', "Desenvolupament d'Aplicacions Multiplataforma"), ('DAW', "Desenvolupament d'Aplicacions Web"), ('ASIX', 'Administració de Sistemes Informàtics i Xarxes'), ('SMX', 'Sistemes Microinformàtics i Xarxes'), ('altres', 'Altres')], max_length=10, verbose_name='Cicle formatiu')),
                ('any_graduacio', models.IntegerField(verbose_name='Any de graduació')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])], verbose_name='Curriculum Vitae')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Perfil LinkedIn')),
                ('github', models.URLField(blank=True, null=True, verbose_name='Perfil GitHub')),
                ('competencies', models.TextField(blank=True, null=True, verbose_name='Competències i habilitats')),
                ('idiomes', models.CharField(blank=True, max_length=200, null=True)),
                ('disponibilitat', models.BooleanField(default=True, verbose_name='Disponible per treballar')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_alumno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Alumne',
                'verbose_name_plural': 'Perfiles Alumnes',
            },
        ),
        migrations.CreateModel(
            name='PerfilEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200, verbose_name='Nombre de la empresa')),
                ('cif', models.CharField(max_length=20, unique=True, verbose_name='CIF/NIF')),
                ('direccion', models.TextField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('web', models.URLField(blank=True, null=True, verbose_name='Página web')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción de la empresa')),
                ('validado', models.BooleanField(default=False, verbose_name='Empresa validada')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_empresa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Empresa',
                'verbose_name_plural': 'Perfiles Empresas',
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name="Títol de l'oferta")),
                ('descripcion', models.TextField(verbose_name='Descripció')),
                ('requisitos', models.TextField(verbose_name='Requisits')),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('remot', 'Remot'), ('hibrid', 'Híbrid')], default='presencial', max_length=15)),
                ('tipo_contrato', models.CharField(choices=[('indefinit', 'Indefinit'), ('temporal', 'Temporal'), ('practiques', 'Pràctiques'), ('freelance', 'Freelance')], default='indefinit', max_length=15, verbose_name='Tipus de contracte')),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicació')),
                ('salario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Salari')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Data de publicació')),
                ('fecha_cierre', models.DateField(blank=True, null=True, verbose_name='Data de tancament')),
                ('activa', models.BooleanField(default=True)),
                ('validada', models.BooleanField(default=False, verbose_name="Oferta validada per l'administrador")),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='core.perfilempresa')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertes',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, verbose_name="Data d'inscripció")),
                ('estado', models.CharField(choices=[('pendent', 'Pendent'), ('revisat', 'Revisat'), ('acceptat', 'Acceptat'), ('rebutjat', 'Rebutjat')], default='pendent', max_length=10)),
                ('carta_presentacion', models.TextField(blank=True, null=True, verbose_name='Carta de presentació')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='core.oferta')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='core.perfilalumno')),
            ],
            options={
                'verbose_name': 'Inscripció',
                'verbose_name_plural': 'Inscripcions',
                'ordering': ['-fecha_inscripcion'],
                'unique_together': {('alumno', 'oferta')},
            },
        ),
    ]
