# Generated by Django 5.0.1 on 2025-10-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_email_verified_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilalumno',
            name='cicle',
            field=models.CharField(choices=[('DAM', "CFGS Desenvolupament d'Aplicacions Multiplataforma (DAM)"), ('SMX', 'CFGM Sistemes microinformàtics i xarxes (SMX)'), ('APD', 'CFGM Atenció a la dependència (APD) en Dual'), ('CAI', "CFGM Cures Auxiliars d'Infermeria"), ('FP_DUAL', 'FP Dual'), ('ESO', 'ESO'), ('BATX', 'Batxillerat'), ('altres', 'Altres')], max_length=10, verbose_name='Cicle formatiu'),
        ),
    ]
