# Generated by Django 5.0.1 on 2025-10-10 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_perfilalumno_cicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilalumno',
            name='cicle',
            field=models.CharField(choices=[('DAM', "CFGS Desenvolupament d'Aplicacions Multiplataforma (DAM)"), ('SMX', 'CFGM Sistemes microinformàtics i xarxes (SMX)'), ('APD', 'CFGM Atenció a la dependència (APD) en Dual'), ('CAI', "CFGM Cures Auxiliars d'Infermeria"), ('ESO', 'ESO'), ('BATX', 'Batxillerat'), ('altres', 'Altres')], max_length=10, verbose_name='Cicle formatiu'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(verbose_name='Missatge')),
                ('leida', models.BooleanField(default=False, verbose_name='Llegida')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('tipo', models.CharField(choices=[('inscripcion', 'Nova inscripció'), ('estado_cambio', "Canvi d'estat"), ('oferta_validada', 'Oferta validada'), ('empresa_validada', 'Empresa validada')], max_length=20, verbose_name='Tipus')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='Enllaç')),
                ('inscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.inscripcion')),
                ('oferta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.oferta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificació',
                'verbose_name_plural': 'Notificacions',
                'ordering': ['-fecha'],
            },
        ),
    ]
