# Generated by Django 5.0.1 on 2025-10-18 17:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_perfilalumno_cicle_notificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilalumno',
            options={'verbose_name': 'Perfil Alumne', 'verbose_name_plural': 'Perfils Alumnes'},
        ),
        migrations.AlterModelOptions(
            name='perfilempresa',
            options={'verbose_name': 'Perfil Empresa', 'verbose_name_plural': 'Perfils Empreses'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuari', 'verbose_name_plural': 'Usuaris'},
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='code',
            field=models.CharField(max_length=6, verbose_name='Codi'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creat el'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Expira el'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL, verbose_name='Usuari'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='core.perfilalumno', verbose_name='Alumne'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('pendent', 'Pendent'), ('revisat', 'Revisat'), ('acceptat', 'Acceptat'), ('rebutjat', 'Rebutjat')], default='pendent', max_length=10, verbose_name='Estat'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='core.oferta', verbose_name='Oferta'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='inscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.inscripcion', verbose_name='Inscripció'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='oferta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.oferta', verbose_name='Oferta'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuari'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='core.perfilempresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('remot', 'Remot'), ('hibrid', 'Híbrid')], default='presencial', max_length=15, verbose_name='Modalitat'),
        ),
        migrations.AlterField(
            model_name='perfilalumno',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de registre'),
        ),
        migrations.AlterField(
            model_name='perfilalumno',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='perfilalumno',
            name='idiomes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Idiomes'),
        ),
        migrations.AlterField(
            model_name='perfilalumno',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_alumno', to=settings.AUTH_USER_MODEL, verbose_name='Usuari'),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name="Descripció de l'empresa"),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Direcció'),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de registre'),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='nombre_empresa',
            field=models.CharField(max_length=200, verbose_name="Nom de l'empresa"),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_empresa', to=settings.AUTH_USER_MODEL, verbose_name='Usuari'),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='web',
            field=models.URLField(blank=True, null=True, verbose_name='Pàgina web'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telèfon'),
        ),
    ]
