# Generated by Django 5.0.1 on 2025-11-12 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_perfilalumno_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Codi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat el')),
                ('expires_at', models.DateTimeField(verbose_name='Expira el')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_recovery', to=settings.AUTH_USER_MODEL, verbose_name='Usuari')),
            ],
            options={
                'verbose_name': 'Recuperació Contrasenya',
                'verbose_name_plural': 'Recuperacions Contrasenya',
            },
        ),
    ]
